package ly.post.dinar.domain.enumeration;

/**
 * The TransactionType enumeration.
 */
public enum TransactionType {
    CONSUMER_WALLET_TO_CONSUMER_WALLET,
    CONSUMER_WALLET_TO_MERCHANT_WALLET,
    CONSUMER_WALLET_TO_CONSUMER,
    CONSUMER_WALLET_TO_BANK,
    CONSUMER_BUY_VOUCHERS,
    MERCHANT_WALLET_TO_CONSUMER_WALLET,
    MERCHANT_WALLET_TO_MERCHANT_WALLET,
    MERCHANT_WALLET_TO_CONSUMER,
    MERCHANT_WALLET_TO_BANK,
    MERCHANT_BUY_VOUCHERS,
}
