export enum AttachmentType {
  COMMERCIAL_REGISTRY = 'COMMERCIAL_REGISTRY',

  COMMERCIAL_LICENCE = 'COMMERCIAL_LICENCE',

  FACE = 'FACE',

  FACE_WITH_ID = 'FACE_WITH_ID',

  PASSPORT = 'PASSPORT',

  ID = 'ID',

  DRIVING_LICENCE = 'DRIVING_LICENCE',
}
